// TENGO QUE TENER DOS ESTADOS UNO DE EL ARRAY DE ACTIVIDAD Y EL OTRO ARRAY DE PAISES
//FORMULARIO CONTROLADO PARA LA ACTIVIDAD
// MAPEADO DE SELECT DE CADA PAIS Y AGREGALO A EL ESTADO DE PAISES
//MOSTRAR EL PAIS SELECCIONADO Y ASIGNARLE UNA "X" QUE ES UN FILTER PARA SACARLO DE ESE ESTADO.
//POR ULTIMO USAR LA ACCION DE POST 